package es.concesionario.pojo;


/**
 * Coche generated by hbm2java
 * @author teide
 * @version 1.0
 * @created 25-jul-2014 13:08:26
 */
@Entity@Table(name="coche"
    ,catalog="concesionarioap"
    , uniqueConstraints = @UniqueConstraint(columnNames="matricula") 
)
public class Coche implements java.io.Serializable {

	private Integer id;
	private String marca;
	private String modelo;
	private String matricula;
	private int cilindrada;
	private boolean aireAcondicionado;



	public void finalize() throws Throwable {

	}

	/**
	 * 
	 * @param id
	 * @param marca
	 * @param modelo
	 * @param matricula
	 * @param cilindrada
	 * @param aireAcondicionado
	 */
	public Coche(Integer id, String marca, String modelo, String matricula, int cilindrada, boolean aireAcondicionado){

	}

	/**
	 * 
	 * @param marca
	 * @param modelo
	 * @param matricula
	 * @param cilindrada
	 * @param aireAcondicionado
	 */
	public Coche(String marca, String modelo, String matricula, int cilindrada, boolean aireAcondicionado){

	}

	public Coche(){

	}

	/**
	 * 
	 * @param aireAcondicionado
	 */
	public void setAireAcondicionado(boolean aireAcondicionado){

	}

	@Column(name="aireAcondicionado", nullable=false)
	public boolean isAireAcondicionado(){
		return false;
	}

	/**
	 * 
	 * @param cilindrada
	 */
	public void setCilindrada(int cilindrada){

	}

	@Column(name="cilindrada", nullable=false)
	public int getCilindrada(){
		return 0;
	}

	/**
	 * 
	 * @param matricula
	 */
	public void setMatricula(String matricula){

	}

	@Column(name="matricula", unique=true, nullable=false, length=10)
	public String getMatricula(){
		return "";
	}

	/**
	 * 
	 * @param modelo
	 */
	public void setModelo(String modelo){

	}

	@Column(name="modelo", nullable=false, length=20)
	public String getModelo(){
		return "";
	}

	/**
	 * 
	 * @param marca
	 */
	public void setMarca(String marca){

	}

	@Column(name="marca", nullable=false, length=20)
	public String getMarca(){
		return "";
	}

	/**
	 * 
	 * @param id
	 */
	public void setId(Integer id){

	}

	@Id@GeneratedValue(strategy=IDENTITY)@Column(name="id", unique=true, nullable=false)
	public Integer getId(){
		return 0;
	}

}